### ISSUE TITLE
Can support archive load/mount? If use storage level to compress, has high read speed.

### ISSUE THREAD

**Issue by lyne408** [ModOrganizer2/usvfs#38]
If too many mods, you'll get too many little files.
1. Then your disk partition gets many fragmentations.
2. The speed of reading little files is much lower than storage level archives.
3. Single archive is better for backuping a mod to another disk partition, and better for management.

If a mod is a storage level archive, the above issues will be prevented.

**Comment by isanae** [comment]
If you're suggesting that usvfs understand archives and treat the files in them as if they were directly on the filesystem, that's just not possible without a huge amount of work. usvfs is basically a file handle generator, it doesn't hook any sort of operation for reading/writing files, which would be required to handle archives transparently. It would need its own kind of handle to distinguish between real files and files from archives and would need to check them for every IO operation, which would probably make performance worse overall.

If you use an SSD, 1 is irrelevant and 2 is mostly mitigated. As for 3, I don't see how archiving files would makes any difference in any case.
